sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t javeke/fib-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true javeke/fib-client-test npm run test

after_success:
  - docker build -t javeke/fib-nginx ./nginx
  - docker build -t javeke/fib-worker ./worker
  - docker build -t javeke/fib-server ./server
  - docker build -t javeke/fib-client ./client

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push javeke/fib-nginx
  - docker push javeke/fib-worker
  - docker push javeke/fib-server
  - docker push javeke/fib-client