version: "3"

services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports: 
            - '8080:80'
    api:
        build: 
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /home/node/server/node_modules
            - ./server:/home/node/server
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    worker:
        build: 
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /home/node/worker/node_modules
            - ./worker:/home/node/worker
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    client:
        stdin_open: true
        build: 
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /home/node/client/node_modules
            - ./client:/home/node/client
        
